# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hava < Formula
  desc "hava is a Go CLI tool to interact with app.hava.io platform."
  homepage "https://github.com/teamhava/hava-ui-cli"
  version "0.0.24-pre-alpha"
  license "Apache-2.0"
  depends_on :macos

  on_macos do
    url "https://github.com/teamhava/hava-ui-cli/releases/download/0.0.24-pre-alpha/hava_Darwin_all.zip"
    sha256 "0124787d9be3c5654ded859ee6edf8fc9be379248333d7046f7503a84c9ee356"

    def install
      bin.install "hava"
    end
  end
end
