# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hava < Formula
  desc "hava is a Go CLI tool to interact with app.hava.io platform."
  homepage "https://github.com/teamhava/hava-ui-cli"
  version "0.0.25-pre-alpha"
  license "Apache-2.0"
  depends_on :macos

  on_macos do
    url "https://github.com/teamhava/hava-ui-cli/releases/download/0.0.25-pre-alpha/hava_Darwin_all.zip"
    sha256 "aeade3b82539b4b57fcafae72f7e4cfcbb08e6d49ffbf1efee8f8bb29daa0f76"

    def install
      bin.install "hava"
    end
  end
end
