# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hava < Formula
  desc "hava is a Go CLI tool to interact with app.hava.io platform."
  homepage "https://github.com/teamhava/hava-ui-cli"
  version "0.1.2"
  license "Apache-2.0"
  depends_on :macos

  on_macos do
    url "https://github.com/teamhava/hava-ui-cli/releases/download/0.1.2/hava_Darwin_all.zip"
    sha256 "cbcc52934a4d5ea1cb93f5f2ea4a90c60a28873819c25b303472b881482e64a6"

    def install
      bin.install "hava"
    end
  end
end
